# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enroll', '0004_auto_20171122_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='single_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('correct_answer', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1)),
                ('A', models.CharField(max_length=100)),
                ('B', models.CharField(max_length=100)),
                ('C', models.CharField(max_length=100)),
                ('D', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='single_choices',
            field=models.ManyToManyField(to='exam.single_choice'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enroll.enrollment'),
        ),
    ]
