# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsDate',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 16, 11, 52, 456383)),
        ),
    ]
