# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseContent', models.TextField(max_length=500)),
                ('courseStart', models.DateTimeField()),
                ('courseTime', models.CharField(max_length=20)),
                ('coursePlace', models.CharField(max_length=50)),
                ('courseStudents', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50)),
                ('newsContent', models.TextField(max_length=500)),
                ('newsDate', models.DateField(default=datetime.datetime(2017, 11, 24, 11, 30, 13, 173666))),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleName', models.CharField(max_length=50)),
                ('scheduleContent', models.TextField(max_length=1000)),
                ('scheduleDeadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50)),
                ('taskContent', models.TextField(max_length=500)),
                ('taskDeadline', models.DateTimeField()),
                ('taskStudents', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
