# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171124_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsDate',
            field=models.DateField(default=datetime.datetime(2017, 11, 24, 14, 40, 41, 562801)),
        ),
    ]
