# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171124_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsDate',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 3, 5, 59, 513046)),
        ),
    ]
