# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollCode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('enrollName', models.CharField(max_length=20)),
                ('enrollGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('enrollCollege', models.CharField(max_length=30)),
                ('enrollEmail', models.EmailField(max_length=100)),
                ('enrollIntro', models.IntegerField(choices=[(0, 'Freshman to programming'), (1, 'Some experiences in one or more languages'), (2, 'Experienced developer'), (3, 'Unavailable')], default=0)),
                ('interviewScoreOne', models.IntegerField(default=0, null=True)),
                ('interviewScoreTwo', models.IntegerField(default=0, null=True)),
                ('examScore', models.IntegerField(default=0, null=True)),
                ('isPassed', models.BooleanField(default=False)),
            ],
        ),
    ]
