# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('enroll_Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('enroll_Name', models.CharField(max_length=20)),
                ('enroll_College', models.CharField(max_length=30)),
                ('enroll_Email', models.CharField(max_length=100)),
            ],
        ),
    ]
