# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enroll_Intro',
            field=models.IntegerField(choices=[(0, 'Freshman to programming'), (1, 'Some experiences in one or more languages'), (2, 'Experienced developer'), (3, 'Unavailable')], default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enroll_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
