# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20171117_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_Code',
            new_name='enrollCode',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_College',
            new_name='enrollCollege',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_Email',
            new_name='enrollEmail',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_gender',
            new_name='enrollGender',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_Intro',
            new_name='enrollIntro',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_Name',
            new_name='enrollName',
        ),
    ]
