# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_enrollment_enrolluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
