# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20171117_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='examScore',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='interviewScoreOne',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='interviewScoreTwo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='isPassed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollEmail',
            field=models.EmailField(max_length=100),
        ),
    ]
